language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev

install:
  - echo deb http://fr.archive.ubuntu.com/ubuntu/ artful main universe | sudo tee /etc/apt/sources.list.d/artful.list
  - 'echo -e "Package: *\nPin: release n=artful\nPin-Priority: 400" | sudo tee /etc/apt/preferences.d/pin.pref'
  - sudo apt-get update
  - sudo apt-get install -t artful libgammu-dev
  - pip install -r pip-requirements.txt
  - pip install -r tests/pip-requirements.txt

script:
  - pylint SMSShell || true
  - python -m pytest --verbose --cov=./ --capture=sys tests/

after_success:
  - codecov
