dist: xenial
language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev

install:
  - sudo apt-get install libgammu-dev
  - pip install -r pip-requirements.txt
  - pip install -r tests/pip-requirements.txt

script:
  - pylint SMSShell bin || true
  - mypy --ignore-missing-imports SMSShell
  - find bin/ -type f | xargs -n 1 mypy --ignore-missing-imports
  - python -m pytest --verbose --cov=./ --capture=sys tests/

after_success:
  - codecov
