dist: xenial
language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8

install:
  - echo deb http://fr.archive.ubuntu.com/ubuntu/ bionic main universe | sudo tee /etc/apt/sources.list.d/bionic.list
  - 'echo -e "Package: *\nPin: release n=bionic\nPin-Priority: 400" | sudo tee /etc/apt/preferences.d/pin.pref'
  - sudo apt-get update
  - sudo apt-get install -t bionic libgammu-dev
  - pip install -r pip-requirements.txt
  - pip install -r tests/pip-requirements.txt

script:
  - pylint SMSShell bin || true
  - mypy --ignore-missing-imports SMSShell
  - python -m pytest --verbose --cov=./ --capture=sys tests/

after_success:
  - codecov
